"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-28 22:52:38.043708
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import assistant.core.models

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fsm_state",
        sa.Column("chat_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("state", sa.String(length=128), nullable=True),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("updated_at", assistant.core.models.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("chat_id", "user_id", name=op.f("pk_fsm_state")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("first_name", sa.String(length=128), nullable=True),
        sa.Column("language", sa.String(length=8), nullable=True),
        sa.Column("tg_language", sa.String(length=16), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("lat", sa.Double(), nullable=False),
        sa.Column("lon", sa.Double(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("morning_enabled", sa.Boolean(), nullable=False),
        sa.Column("morning_time", sa.String(length=5), nullable=False),
        sa.Column("last_morning_date", sa.Date(), nullable=True),
        sa.Column("bot_blocked", sa.Boolean(), nullable=False),
        sa.Column("created_at", assistant.core.models.UTCDateTime(), nullable=False),
        sa.Column("updated_at", assistant.core.models.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_table(
        "habits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_on", sa.Date(), nullable=False),
        sa.Column("created_at", assistant.core.models.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_habits_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_habits")),
    )
    with op.batch_alter_table("habits", schema=None) as batch_op:
        batch_op.create_index("ix_habits_user", ["user_id"], unique=False)

    op.create_table(
        "notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", assistant.core.models.UTCDateTime(), nullable=False),
        sa.Column("updated_at", assistant.core.models.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notes_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notes")),
    )
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.create_index("ix_notes_user", ["user_id", "id"], unique=False)

    op.create_table(
        "reminders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("due_at", assistant.core.models.UTCDateTime(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", assistant.core.models.UTCDateTime(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("sent_at", assistant.core.models.UTCDateTime(), nullable=True),
        sa.Column("created_at", assistant.core.models.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_reminders_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reminders")),
    )
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.create_index("ix_reminders_queue", ["status", "next_attempt_at"], unique=False)
        batch_op.create_index("ix_reminders_user", ["user_id", "status", "due_at"], unique=False)

    op.create_table(
        "habit_marks",
        sa.Column("habit_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("done", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["habit_id"],
            ["habits.id"],
            name=op.f("fk_habit_marks_habit_id_habits"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("habit_id", "day", name=op.f("pk_habit_marks")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("habit_marks")
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.drop_index("ix_reminders_user")
        batch_op.drop_index("ix_reminders_queue")

    op.drop_table("reminders")
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.drop_index("ix_notes_user")

    op.drop_table("notes")
    with op.batch_alter_table("habits", schema=None) as batch_op:
        batch_op.drop_index("ix_habits_user")

    op.drop_table("habits")
    op.drop_table("users")
    op.drop_table("fsm_state")
    # ### end Alembic commands ###
